-- Carga masiva de servicios del estudio, exportados de AgendaPro.
-- Precio y duracion (minutos) tal cual figuran en el reporte; IVA y comision se ignoran
-- a proposito (no aplican al modelo de esta app). Idempotente: no duplica si ya corrio
-- (se identifica por nombre + categoria).

insert into services (name, category, duration_minutes, price, active)
select v.name, v.category, v.duration_minutes, v.price, true
from (values
  ('Limpieza con dermanplaning + perfilado de cejas', 'Rostro y Piel', 100, 51000),
  ('Limpieza con dermanplaning + hydragloss', 'Rostro y Piel', 105, 39000),
  ('Belleza de manos+ esmaltado Semi', 'Uñas', 50, 24000),
  ('Esmaltado semi en manos y pies', 'Uñas', 90, 44000),
  ('Cejas hibridas Primera Sesion por staff', 'Micropigmentacion', 120, 150000),
  ('Cejas hibridas Segunda Sesion por staff', 'Micropigmentacion', 120, 150000),
  ('Full Face (micropigmentación de cejas, labios y párpados - valor POR SESIÓN, se realiza en 2 sesiones)', 'Promos', 420, 540000),
  ('Maderoterapia + botas de presoterapia', 'Promos', 60, 50000),
  ('Lifting de pestañas + perfilado de cejas', 'Promos', 60, 52000),
  ('Lifting de pestañas + Henna en cejas (opcional perfilado)', 'Promos', 75, 61000),
  ('Videoconsulta personalizada', 'Micropigmentacion', 20, 1),
  ('seminario', 'Micropigmentacion', 5, 0),
  ('Remoción Laser', 'Micropigmentacion', 30, 85000),
  ('extensión de curso', 'Micropigmentacion', 5, 0),
  ('redondeo', 'Corporal', 5, 0),
  ('Corrección de Micropigmentación primera sesión', 'Rostro y Piel', 150, 490000),
  ('Cejas Hibridas Primera y Segunda Sesion', 'Micropigmentacion', 150, 430000),
  ('Micropigmentacion de Labios Primera y Segunda Sesion', 'Micropigmentacion', 150, 390000),
  ('Dermopigmentacion Primera y Segunda Sesión', 'Micropigmentacion', 150, 390000),
  ('Microblading Primera y Segunda Sesión', 'Micropigmentacion', 120, 390000),
  ('Hairstrokes Primera y Segunda sesión', 'Micropigmentacion', 150, 390000),
  ('Delineado de Ojos Primera y Segunda sesión con Mica', 'Micropigmentacion', 150, 390000),
  ('Esmaltado semi en pies', 'Uñas', 75, 24000),
  ('Lifting de pestañas + perfilado', 'Pestañas', 75, 52000),
  ('Curso presencial Tricopigmentación', 'Cursos Presenciales', 5, 0),
  ('Belleza de pies', 'Uñas', 45, 20000),
  ('Consulta', 'Micropigmentacion', 15, 0),
  ('Sesion adicional Micropigmentacion de Labios', 'Micropigmentacion', 90, 200000),
  ('Sesion adicional Microblading', 'Micropigmentacion', 90, 200000),
  ('Sesion adicional Hairstrokes', 'Micropigmentacion', 90, 200000),
  ('Sesion adicional Dermo de cejas', 'Micropigmentacion', 90, 200000),
  ('Retoque Tatuaje', 'Micropigmentacion', 60, 0),
  ('Seña Curso Tricopigmentacion', 'Cursos Presenciales', 5, 1),
  ('Seña Curso Eyeliner', 'Cursos Presenciales', 5, 1),
  ('Seña Curso Labios', 'Cursos Presenciales', 5, 1),
  ('Seña Curso Hairstrokes', 'Cursos Presenciales', 5, 1),
  ('Seña Curso Dermo de cejas', 'Cursos Presenciales', 5, 1),
  ('Adicional escote', 'Rostro y Piel', 11, 14000),
  ('Epilacion bozo con Mica', 'Rostro y Piel', 30, 16000),
  ('Micropigmentación de ojos + micropigmentacion de cejas by STAFF', 'Promos', 240, 250000),
  ('Manicuria semipermante + Perfilado de cejas', 'Promos', 60, 41000),
  ('Lifting de pestañas + Laminado de cejas', 'Promos', 90, 65000),
  ('Mantenimiento anual de Hairstrokes con Staff', 'Micropigmentacion', 120, 150000),
  ('Hairstrokes Segunda Sesion con Staff', 'Micropigmentacion', 120, 150000),
  ('Hairstrokes Primera Sesion con Staff', 'Micropigmentacion', 120, 150000),
  ('Uñas esculpidas (estructuras largas)', 'Uñas', 80, 44000),
  ('Limpieza de cutis con Mica', 'Rostro y Piel', 90, 1),
  ('Perfilado + Laminado + Henna con Mica', 'Cejas', 90, 44000),
  ('Perfilado + Laminado con Mica', 'Cejas', 60, 39000),
  ('Perfilado + Henna con Mica', 'Cejas', 30, 34000),
  ('Lifting de pestañas con Mica', 'Pestañas', 70, 34000),
  ('Perfilado de Cejas con Mica', 'Cejas', 30, 22000),
  ('Seña Turnos', 'Pestañas', 5, 10000),
  ('Seña turno perfilado', 'Cejas', 5, 5000),
  ('Adicional Nail Art Diseño por Uña', 'Uñas', 15, 4000),
  ('Adicional Full Nail Art Diseño', 'Uñas', 45, 18000),
  ('Adicional Full Nail Art Basico', 'Uñas', 30, 10000),
  ('Adicional Aplique', 'Uñas', 5, 2000),
  ('Adicional por Arreglo de Uña Quebrada', 'Uñas', 5, 4000),
  ('Retiro Capping, Esculpidas o Soft Gel', 'Uñas', 30, 13000),
  ('Retiro semi', 'Uñas', 30, 10000),
  ('Uñas Soft Gel', 'Uñas', 90, 32000),
  ('Uñas Esculpidas (cortas o medium)', 'Uñas', 80, 40000),
  ('Capping + Esmaltado Semipermanente', 'Uñas', 100, 29000),
  ('Esmaltado semi en manos', 'Uñas', 45, 24000),
  ('Belleza + esmaltado tradicional', 'Uñas', 45, 22000),
  ('Belleza de manos', 'Uñas', 40, 20000),
  ('Laminado en cejas (sin perfilado)', 'Cejas', 35, 34000),
  ('Henna en cejas (sin perfilado)', 'Cejas', 30, 29000),
  ('Mantenimiento anual de Cejas Hibridas', 'Micropigmentacion', 120, 220000),
  ('Modelo', 'Micropigmentacion', 10, 1),
  ('Curso personalizado eyeliner', 'Cursos Personalizados', 5, 1),
  ('Perfilado + Henna', 'Cejas', 35, 34000),
  ('Cancelacion', 'Micropigmentacion', 5, 0),
  ('extensiones pestañas con Mica', 'Pestañas', 120, 1),
  ('Tatuaje', 'Micropigmentacion', 90, 1),
  ('Extensiones de diseño', 'Pestañas', 75, 46000),
  ('Extensiones de pestañas clasicas', 'Pestañas', 75, 34000),
  ('perforacion', 'Pestañas', 15, 1),
  ('HydraGloss + Limpieza básica', 'Rostro y Piel', 60, 20000),
  ('webinar powder', 'Cursos Online', 5, 25000),
  ('Rodri Productos', 'Cejas', 5, 1),
  ('Perfilado + Laminado + Henna', 'Cejas', 90, 44000),
  ('Perfilado + Laminado', 'Cejas', 70, 39000),
  ('PROPINA', 'Corporal', 5, 1),
  ('Cejas Híbridas Segunda Sesión con Mica', 'Micropigmentacion', 90, 220000),
  ('Cejas Híbridas Primera Sesión con Mica', 'Micropigmentacion', 120, 220000),
  ('Mantenimiento anual de Delineado de Ojos con Staff', 'Micropigmentacion', 120, 150000),
  ('Mantenimiento anual de Delineado de Ojos con Mica', 'Micropigmentacion', 120, 200000),
  ('Mantenimiento anual de Hairstrokes con Mica', 'Micropigmentacion', 150, 200000),
  ('Mantenimiento anual de Micropigmentación de Labios con Staff', 'Micropigmentacion', 120, 150000),
  ('Mantenimiento anual de Micropigmentación de labios con Mica', 'Micropigmentacion', 150, 200000),
  ('Mantenimiento anual de Dermo de cejas con Staff', 'Micropigmentacion', 120, 150000),
  ('Mantenimiento anual de Dermo de cejas con Mica', 'Micropigmentacion', 120, 200000),
  ('Mantenimiento anual de Microblading con Staff', 'Micropigmentacion', 120, 150000),
  ('Mantenimiento anual de Microblading con Mica', 'Micropigmentacion', 90, 200000),
  ('Corrección de Micropigmentación sesión adicional con Staff', 'Micropigmentacion', 120, 200000),
  ('Corrección de Micropigmentación primera sesión con Staff', 'Micropigmentacion', 150, 200000),
  ('Corrección de Micropigmentación Sesión Adicional con Mica', 'Micropigmentacion', 120, 250000),
  ('Corrección de Micropigmentación primera sesión con Mica', 'Micropigmentacion', 150, 250000),
  ('Seña Curso Microblading', 'Cursos Presenciales', 5, 1),
  ('Masterclass Personalizada', 'Cursos Personalizados', 5, 1),
  ('Curso Online de Hairstrokes', 'Cursos Online', 5, 0),
  ('Curso Personalizado De Haistrokes', 'Cursos Personalizados', 5, 1),
  ('Curso Personalizado Labios', 'Cursos Personalizados', 5, 1),
  ('Curso Personalizado Dermo de Cejas', 'Cursos Personalizados', 5, 1),
  ('Curso Personalizado Microblading', 'Cursos Personalizados', 5, 1),
  ('Curso Presencial Masterclass Fussion Brows', 'Cursos Presenciales', 5, 1),
  ('Curso Presencial Masterclass Full Face', 'Cursos Presenciales', 5, 1),
  ('Curso Personalizado Tricopigmentacion', 'Cursos Personalizados', 5, 1),
  ('Curso Presencial Hairstrokes', 'Cursos Presenciales', 5, 1),
  ('Curso Presencial Eyeliner', 'Cursos Presenciales', 5, 1),
  ('Curso Presencial Labios', 'Cursos Presenciales', 5, 1),
  ('Curso Presencial Dermo de Cejas', 'Cursos Presenciales', 5, 1),
  ('Curso Presencial Microblading', 'Cursos Presenciales', 5, 1),
  ('Curso Online Eyeliner', 'Cursos Online', 5, 1),
  ('Curso Online Labios', 'Cursos Online', 5, 1),
  ('Curso Online Dermo de Cejas', 'Cursos Online', 5, 1),
  ('Curso Online Microblading', 'Cursos Online', 5, 1),
  ('Retiro de Extensiones', 'Pestañas', 30, 24000),
  ('Extensiones de Diseño con Danielle', 'Pestañas', 150, 35000),
  ('Extensiones Volumen Power Service', 'Pestañas', 90, 42000),
  ('Extensiones Volumen Power', 'Pestañas', 90, 44000),
  ('Extensiones Volumen Full Service', 'Pestañas', 90, 40000),
  ('Extensiones Volumen Full Service con Danielle', 'Pestañas', 90, 25000),
  ('Extensiones Volumen Full', 'Pestañas', 90, 42000),
  ('Extensiones Volumen Full con Danielle', 'Pestañas', 120, 26000),
  ('Extensiones Volumen Medio Service', 'Pestañas', 60, 38000),
  ('Extensiones Volumen Medio Service con Danielle', 'Pestañas', 90, 23000),
  ('Extensiones Volumen Medio', 'Pestañas', 70, 40000),
  ('Extensiones Volumen Medio con Danielle', 'Pestañas', 120, 24000),
  ('Extensiones Volumen Light Services', 'Pestañas', 60, 36000),
  ('Extensiones Volumen Light', 'Pestañas', 70, 38000),
  ('Extensiones Volumen Light Service Con Danielle', 'Pestañas', 120, 21000),
  ('Extensiones Volumen Light con Danielle', 'Pestañas', 120, 22000),
  ('Extensiones Hibridas Service', 'Pestañas', 75, 34000),
  ('Extensiones Hibridas', 'Pestañas', 70, 36000),
  ('Extensiones Hibridas Service con Danielle', 'Pestañas', 90, 19000),
  ('Extensiones Hibridas con Danielle', 'Pestañas', 120, 20000),
  ('Extensiones Clasicas Service', 'Pestañas', 75, 32000),
  ('Aplicacion de Keratina o Botox', 'Pestañas', 30, 14000),
  ('Lifting Correctivo', 'Pestañas', 80, 39000),
  ('Lifting de Pestañas', 'Pestañas', 80, 34000),
  ('Maquillaje + Peinado', 'Rostro y Piel', 120, 130000),
  ('Peinado', 'Rostro y Piel', 60, 70000),
  ('Maquillaje', 'Rostro y Piel', 60, 75000),
  ('Epilacion Rostro Completo', 'Rostro y Piel', 30, 34000),
  ('Epilacion de Bozo', 'Rostro y Piel', 30, 16000),
  ('Limpieza de Espalda + Dermaplaning + Microneedlng', 'Rostro y Piel', 90, 60000),
  ('Limpieza de Espalda + Dermaplaning', 'Rostro y Piel', 90, 40000),
  ('Limpieza Tradicional de Espalda', 'Rostro y Piel', 60, 34000),
  ('Limpieza facial con Microneedlng + Dermaplaning', 'Rostro y Piel', 90, 52000),
  ('Limpieza facial con Dermaplaning', 'Rostro y Piel', 90, 29000),
  ('Limpieza facial con Microneedlng', 'Rostro y Piel', 90, 34000),
  ('Limpieza de cutis Tradicional', 'Rostro y Piel', 60, 24000),
  ('Masaje Faciales con Ventosas y Guasha', 'Rostro y Piel', 60, 28000),
  ('Perfilado de Cejas', 'Cejas', 30, 22000),
  ('Microneedlng Reductor', 'Corporal', 60, 50000),
  ('Ultracavitador', 'Corporal', 60, 39000),
  ('Tratamiento Capilar', 'Corporal', 60, 65000),
  ('Tratamiento de Estrias y Cicatrices', 'Corporal', 60, 200000),
  ('Pulido Corporal', 'Corporal', 60, 34000),
  ('Maderoterapia', 'Corporal', 60, 34000),
  ('Drenaje Linfatico', 'Corporal', 60, 34000),
  ('Masaje Modelador', 'Corporal', 60, 34000),
  ('Masaje Deportivo', 'Corporal', 60, 34000),
  ('Masaje Descontracturante', 'Corporal', 60, 34000),
  ('Masaje Relajante', 'Corporal', 60, 34000),
  ('Remoción de trabajos previos', 'Micropigmentacion', 60, 85000),
  ('Reconstruccion Areolar', 'Micropigmentacion', 90, 200000),
  ('Tricopigmentacion (Valor a Confirmar)', 'Micropigmentacion', 60, 200000),
  ('Delineado de Ojos Segunda sesion Por Staff', 'Micropigmentacion', 120, 150000),
  ('Delineado de Ojos Primera Sesion Por Staff', 'Micropigmentacion', 150, 150000),
  ('Delineado de Ojos Segunda Sesion Por Mica', 'Micropigmentacion', 120, 200000),
  ('Delineado de Ojos Primera Sesion Por Mica', 'Micropigmentacion', 150, 200000),
  ('Hairstrokes Segunda Sesion con Mica', 'Micropigmentacion', 120, 200000),
  ('Hairstrokes Primera Sesion con Mica', 'Micropigmentacion', 150, 200000),
  ('Dermopigmentacion de Cejas Segunda sesion Por Staff', 'Micropigmentacion', 90, 150000),
  ('Dermopigmentacion de Cejas Primera sesion Por Staff', 'Micropigmentacion', 120, 150000),
  ('Dermopigmentacion de Cejas Segunda sesion Por Mica', 'Micropigmentacion', 90, 200000),
  ('Dermopigmentacion de Cejas Primera sesion Por Mica', 'Micropigmentacion', 120, 200000),
  ('Micropigmentacion de Labios Segunda Sesion Por Staff', 'Micropigmentacion', 120, 150000),
  ('Micropigmentacion de Labios Primera Sesion Por Staff', 'Micropigmentacion', 150, 150000),
  ('Micropigmentacion de Labios Segunda Sesion Por Mica', 'Micropigmentacion', 120, 200000),
  ('Micropigmentacion de Labios Primera Sesion Por Mica', 'Micropigmentacion', 150, 200000),
  ('Microblading Segunda sesion Por Staff', 'Micropigmentacion', 90, 150000),
  ('Microblading Primera sesion Por Staff', 'Micropigmentacion', 120, 150000),
  ('Seña Turno Micropigmentacion', 'Micropigmentacion', 5, 30000),
  ('Microblading Segunda sesion Por Mica', 'Micropigmentacion', 60, 200000),
  ('Microblading Primera sesion Por Mica', 'Micropigmentacion', 90, 200000)
) as v(name, category, duration_minutes, price)
where not exists (
  select 1 from services s
  where s.name = v.name and coalesce(s.category, '') = coalesce(v.category, '')
);
